// /lib/members.js

export const members = [
  {
    name: 'Angel Hopkins',
    gender: 'Female',
    age: 28,
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '15/03/1996',
    work: 'Teacher',
    city: 'Canada, North America',
    img: '/Images/Bride.png',
    slug: 'angel-hopkins',
  },
  {
    name: 'Teszt Elecking',
    gender: 'Female',
    age: 32,
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '31/07/1998',
    work: 'Designer',
    city: 'Canada, North America',
    img: '/Images/Bride.png',
    slug: 'teszt-elecking',
  },
  {
    name: 'Gyan-Baffour',
    gender: 'Male',
    age: 30,
    education: 'Bachelor’s Degree',
    maritalStatus: 'Single',
    dob: '21/06/1994',
    work: 'Developer',
    city: 'Canada, North America',
    img: '/Images/groom.png',
    slug: 'gyan-baffour',
  },
  {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
  {
    name: 'Andrea Guido',
    gender: 'Female',
    age: 26,
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '10/11/1998',
    work: 'Photographer',
    city: 'Canada, North America',
    img: '/Images/Bride.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },

    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },  {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
    {
    name: 'Full Name',
    gender: 'Gender',
    age: 'number',
    education: 'Graduate Degree',
    maritalStatus: 'Single',
    dob: '00/00/0000',
    work: 'Work',
    city: 'X City ,X Country,x',
    img: '/Images/Unknown.png',
    slug: 'andrea-guido',
  },
];
